// Liste des plantes les plus repandues (jardinerie / interieur / jardin belge).
// Sert a pre-remplir le cache : chaque espece est generee UNE fois par Claude
// puis stockee, pour un affichage instantane ensuite.
// Extensible : ajouter des entrees { sci, common, family }.
export const PLANTS = [
  // ---- Plantes d'interieur / feuillage tropical ----
  { sci: "Phalaenopsis amabilis", common: "Orchidee papillon", family: "Orchidaceae" },
  { sci: "Monstera deliciosa", common: "Monstera", family: "Araceae" },
  { sci: "Epipremnum aureum", common: "Pothos", family: "Araceae" },
  { sci: "Ficus lyrata", common: "Figuier lyre", family: "Moraceae" },
  { sci: "Ficus elastica", common: "Caoutchouc", family: "Moraceae" },
  { sci: "Ficus benjamina", common: "Figuier pleureur", family: "Moraceae" },
  { sci: "Dracaena marginata", common: "Dragonnier de Madagascar", family: "Asparagaceae" },
  { sci: "Dracaena fragrans", common: "Dracaena parfume", family: "Asparagaceae" },
  { sci: "Dracaena trifasciata", common: "Sansevieria, langue de belle-mere", family: "Asparagaceae" },
  { sci: "Zamioculcas zamiifolia", common: "Plante ZZ", family: "Araceae" },
  { sci: "Spathiphyllum wallisii", common: "Fleur de lune", family: "Araceae" },
  { sci: "Chlorophytum comosum", common: "Plante araignee", family: "Asparagaceae" },
  { sci: "Aglaonema commutatum", common: "Aglaonema", family: "Araceae" },
  { sci: "Philodendron hederaceum", common: "Philodendron grimpant", family: "Araceae" },
  { sci: "Philodendron scandens", common: "Philodendron", family: "Araceae" },
  { sci: "Philodendron selloum", common: "Philodendron a feuilles decoupees", family: "Araceae" },
  { sci: "Calathea orbifolia", common: "Calathea", family: "Marantaceae" },
  { sci: "Calathea makoyana", common: "Plante paon", family: "Marantaceae" },
  { sci: "Maranta leuconeura", common: "Plante priante", family: "Marantaceae" },
  { sci: "Ctenanthe burle-marxii", common: "Ctenanthe", family: "Marantaceae" },
  { sci: "Anthurium andraeanum", common: "Anthurium", family: "Araceae" },
  { sci: "Dieffenbachia seguine", common: "Dieffenbachia", family: "Araceae" },
  { sci: "Syngonium podophyllum", common: "Syngonium", family: "Araceae" },
  { sci: "Aphelandra squarrosa", common: "Plante zebre", family: "Acanthaceae" },
  { sci: "Fittonia albivenis", common: "Fittonia", family: "Acanthaceae" },
  { sci: "Peperomia obtusifolia", common: "Peperomia", family: "Piperaceae" },
  { sci: "Peperomia caperata", common: "Peperomia ridee", family: "Piperaceae" },
  { sci: "Pilea peperomioides", common: "Plante a monnaie chinoise", family: "Urticaceae" },
  { sci: "Tradescantia zebrina", common: "Misere", family: "Commelinaceae" },
  { sci: "Tradescantia fluminensis", common: "Ephemere", family: "Commelinaceae" },
  { sci: "Scindapsus pictus", common: "Scindapsus", family: "Araceae" },
  { sci: "Schefflera arboricola", common: "Schefflera", family: "Araliaceae" },
  { sci: "Hedera helix", common: "Lierre", family: "Araliaceae" },
  { sci: "Fatsia japonica", common: "Aralia du Japon", family: "Araliaceae" },
  { sci: "Hoya carnosa", common: "Fleur de porcelaine", family: "Apocynaceae" },
  { sci: "Beaucarnea recurvata", common: "Pied d'elephant", family: "Asparagaceae" },
  { sci: "Yucca elephantipes", common: "Yucca", family: "Asparagaceae" },
  { sci: "Cordyline fruticosa", common: "Cordyline", family: "Asparagaceae" },
  { sci: "Aspidistra elatior", common: "Aspidistra", family: "Asparagaceae" },
  { sci: "Codiaeum variegatum", common: "Croton", family: "Euphorbiaceae" },
  { sci: "Begonia rex", common: "Begonia rex", family: "Begoniaceae" },
  { sci: "Begonia maculata", common: "Begonia maculata", family: "Begoniaceae" },
  { sci: "Saintpaulia ionantha", common: "Violette africaine", family: "Gesneriaceae" },
  { sci: "Cyclamen persicum", common: "Cyclamen", family: "Primulaceae" },
  { sci: "Kalanchoe blossfeldiana", common: "Kalanchoe", family: "Crassulaceae" },
  { sci: "Schlumbergera truncata", common: "Cactus de Noel", family: "Cactaceae" },
  { sci: "Clivia miniata", common: "Clivia", family: "Amaryllidaceae" },
  { sci: "Strelitzia reginae", common: "Oiseau de paradis", family: "Strelitziaceae" },
  { sci: "Strelitzia nicolai", common: "Strelitzia geant", family: "Strelitziaceae" },
  { sci: "Musa acuminata", common: "Bananier d'ornement", family: "Musaceae" },
  { sci: "Alocasia amazonica", common: "Alocasia", family: "Araceae" },
  { sci: "Alocasia zebrina", common: "Alocasia zebrina", family: "Araceae" },
  { sci: "Colocasia esculenta", common: "Oreille d'elephant", family: "Araceae" },
  { sci: "Chamaedorea elegans", common: "Palmier de montagne", family: "Arecaceae" },
  { sci: "Howea forsteriana", common: "Kentia", family: "Arecaceae" },
  { sci: "Dypsis lutescens", common: "Palmier d'Areca", family: "Arecaceae" },
  { sci: "Phoenix roebelenii", common: "Dattier nain", family: "Arecaceae" },
  { sci: "Nephrolepis exaltata", common: "Fougere de Boston", family: "Nephrolepidaceae" },
  { sci: "Asplenium nidus", common: "Fougere nid d'oiseau", family: "Aspleniaceae" },
  { sci: "Adiantum raddianum", common: "Capillaire", family: "Pteridaceae" },
  { sci: "Platycerium bifurcatum", common: "Corne d'elan", family: "Polypodiaceae" },

  // ---- Succulentes & cactees ----
  { sci: "Aloe vera", common: "Aloe vera", family: "Asphodelaceae" },
  { sci: "Aloe arborescens", common: "Aloes candelabre", family: "Asphodelaceae" },
  { sci: "Gasteria bicolor", common: "Gasteria", family: "Asphodelaceae" },
  { sci: "Haworthia fasciata", common: "Haworthia zebre", family: "Asphodelaceae" },
  { sci: "Echeveria elegans", common: "Echeveria", family: "Crassulaceae" },
  { sci: "Crassula ovata", common: "Arbre de jade", family: "Crassulaceae" },
  { sci: "Sedum morganianum", common: "Queue d'ane", family: "Crassulaceae" },
  { sci: "Sedum spectabile", common: "Orpin d'automne", family: "Crassulaceae" },
  { sci: "Sempervivum tectorum", common: "Joubarbe", family: "Crassulaceae" },
  { sci: "Graptopetalum paraguayense", common: "Plante fantome", family: "Crassulaceae" },
  { sci: "Kalanchoe daigremontiana", common: "Mere de milliers", family: "Crassulaceae" },
  { sci: "Senecio rowleyanus", common: "Collier de perles", family: "Asteraceae" },
  { sci: "Euphorbia trigona", common: "Euphorbe candelabre", family: "Euphorbiaceae" },
  { sci: "Euphorbia milii", common: "Couronne d'epines", family: "Euphorbiaceae" },
  { sci: "Agave americana", common: "Agave", family: "Asparagaceae" },
  { sci: "Opuntia ficus-indica", common: "Figuier de Barbarie", family: "Cactaceae" },
  { sci: "Mammillaria elongata", common: "Cactus doigts de dame", family: "Cactaceae" },
  { sci: "Echinocactus grusonii", common: "Coussin de belle-mere", family: "Cactaceae" },
  { sci: "Gymnocalycium mihanovichii", common: "Cactus lune", family: "Cactaceae" },
  { sci: "Rhipsalis baccifera", common: "Cactus corail", family: "Cactaceae" },
  { sci: "Lithops", common: "Plante caillou", family: "Aizoaceae" },

  // ---- Orchidees ----
  { sci: "Cymbidium hybride", common: "Cymbidium", family: "Orchidaceae" },
  { sci: "Dendrobium nobile", common: "Dendrobium", family: "Orchidaceae" },
  { sci: "Cattleya labiata", common: "Cattleya", family: "Orchidaceae" },
  { sci: "Oncidium", common: "Orchidee pluie d'or", family: "Orchidaceae" },
  { sci: "Vanda", common: "Vanda", family: "Orchidaceae" },
  { sci: "Miltonia", common: "Orchidee pensee", family: "Orchidaceae" },

  // ---- Aromatiques & potager ----
  { sci: "Ocimum basilicum", common: "Basilic", family: "Lamiaceae" },
  { sci: "Mentha spicata", common: "Menthe verte", family: "Lamiaceae" },
  { sci: "Petroselinum crispum", common: "Persil", family: "Apiaceae" },
  { sci: "Coriandrum sativum", common: "Coriandre", family: "Apiaceae" },
  { sci: "Thymus vulgaris", common: "Thym", family: "Lamiaceae" },
  { sci: "Rosmarinus officinalis", common: "Romarin", family: "Lamiaceae" },
  { sci: "Salvia officinalis", common: "Sauge officinale", family: "Lamiaceae" },
  { sci: "Origanum vulgare", common: "Origan", family: "Lamiaceae" },
  { sci: "Allium schoenoprasum", common: "Ciboulette", family: "Amaryllidaceae" },
  { sci: "Laurus nobilis", common: "Laurier-sauce", family: "Lauraceae" },
  { sci: "Melissa officinalis", common: "Melisse", family: "Lamiaceae" },
  { sci: "Solanum lycopersicum", common: "Tomate", family: "Solanaceae" },
  { sci: "Capsicum annuum", common: "Poivron / piment", family: "Solanaceae" },
  { sci: "Cucumis sativus", common: "Concombre", family: "Cucurbitaceae" },
  { sci: "Fragaria x ananassa", common: "Fraisier", family: "Rosaceae" },
  { sci: "Lactuca sativa", common: "Laitue", family: "Asteraceae" },
  { sci: "Cucurbita pepo", common: "Courgette", family: "Cucurbitaceae" },
  { sci: "Phaseolus vulgaris", common: "Haricot", family: "Fabaceae" },
  { sci: "Rubus idaeus", common: "Framboisier", family: "Rosaceae" },
  { sci: "Ribes rubrum", common: "Groseillier", family: "Grossulariaceae" },
  { sci: "Ribes nigrum", common: "Cassissier", family: "Grossulariaceae" },
  { sci: "Vaccinium corymbosum", common: "Myrtillier", family: "Ericaceae" },

  // ---- Fleurs annuelles & bisannuelles ----
  { sci: "Pelargonium x hortorum", common: "Geranium des jardins", family: "Geraniaceae" },
  { sci: "Pelargonium peltatum", common: "Geranium lierre", family: "Geraniaceae" },
  { sci: "Petunia x hybrida", common: "Petunia", family: "Solanaceae" },
  { sci: "Calibrachoa", common: "Million bells", family: "Solanaceae" },
  { sci: "Tagetes patula", common: "Oeillet d'Inde", family: "Asteraceae" },
  { sci: "Impatiens walleriana", common: "Impatiens", family: "Balsaminaceae" },
  { sci: "Begonia semperflorens", common: "Begonia des jardins", family: "Begoniaceae" },
  { sci: "Viola x wittrockiana", common: "Pensee", family: "Violaceae" },
  { sci: "Viola cornuta", common: "Petite pensee", family: "Violaceae" },
  { sci: "Lobelia erinus", common: "Lobelie", family: "Campanulaceae" },
  { sci: "Salvia splendens", common: "Sauge ecarlate", family: "Lamiaceae" },
  { sci: "Helianthus annuus", common: "Tournesol", family: "Asteraceae" },
  { sci: "Cosmos bipinnatus", common: "Cosmos", family: "Asteraceae" },
  { sci: "Zinnia elegans", common: "Zinnia", family: "Asteraceae" },
  { sci: "Antirrhinum majus", common: "Muflier, gueule-de-loup", family: "Plantaginaceae" },
  { sci: "Dianthus barbatus", common: "Oeillet de poete", family: "Caryophyllaceae" },
  { sci: "Bellis perennis", common: "Paquerette", family: "Asteraceae" },
  { sci: "Primula vulgaris", common: "Primevere", family: "Primulaceae" },
  { sci: "Verbena bonariensis", common: "Verveine de Buenos Aires", family: "Verbenaceae" },
  { sci: "Nicotiana alata", common: "Tabac d'ornement", family: "Solanaceae" },
  { sci: "Fuchsia magellanica", common: "Fuchsia", family: "Onagraceae" },

  // ---- Vivaces ----
  { sci: "Hydrangea macrophylla", common: "Hortensia", family: "Hydrangeaceae" },
  { sci: "Hosta", common: "Hosta", family: "Asparagaceae" },
  { sci: "Lavandula angustifolia", common: "Lavande", family: "Lamiaceae" },
  { sci: "Echinacea purpurea", common: "Echinacee", family: "Asteraceae" },
  { sci: "Rudbeckia fulgida", common: "Rudbeckie", family: "Asteraceae" },
  { sci: "Sedum spectabile", common: "Sedum d'automne", family: "Crassulaceae" },
  { sci: "Salvia nemorosa", common: "Sauge des bois", family: "Lamiaceae" },
  { sci: "Geranium sanguineum", common: "Geranium vivace", family: "Geraniaceae" },
  { sci: "Astilbe arendsii", common: "Astilbe", family: "Saxifragaceae" },
  { sci: "Delphinium elatum", common: "Pied d'alouette", family: "Ranunculaceae" },
  { sci: "Lupinus polyphyllus", common: "Lupin", family: "Fabaceae" },
  { sci: "Paeonia lactiflora", common: "Pivoine", family: "Paeoniaceae" },
  { sci: "Achillea millefolium", common: "Achillee", family: "Asteraceae" },
  { sci: "Aquilegia vulgaris", common: "Ancolie", family: "Ranunculaceae" },
  { sci: "Digitalis purpurea", common: "Digitale", family: "Plantaginaceae" },
  { sci: "Heuchera sanguinea", common: "Heuchere", family: "Saxifragaceae" },
  { sci: "Bergenia cordifolia", common: "Bergenia", family: "Saxifragaceae" },
  { sci: "Gaillardia aristata", common: "Gaillarde", family: "Asteraceae" },
  { sci: "Coreopsis grandiflora", common: "Coreopsis", family: "Asteraceae" },
  { sci: "Nepeta faassenii", common: "Nepeta, herbe a chat", family: "Lamiaceae" },
  { sci: "Verbascum thapsus", common: "Molene", family: "Scrophulariaceae" },
  { sci: "Alchemilla mollis", common: "Alchemille", family: "Rosaceae" },
  { sci: "Helleborus niger", common: "Rose de Noel", family: "Ranunculaceae" },
  { sci: "Anemone hupehensis", common: "Anemone du Japon", family: "Ranunculaceae" },
  { sci: "Aster novi-belgii", common: "Aster d'automne", family: "Asteraceae" },
  { sci: "Chrysanthemum indicum", common: "Chrysantheme", family: "Asteraceae" },
  { sci: "Dahlia pinnata", common: "Dahlia", family: "Asteraceae" },

  // ---- Bulbes ----
  { sci: "Tulipa gesneriana", common: "Tulipe", family: "Liliaceae" },
  { sci: "Narcissus pseudonarcissus", common: "Jonquille / narcisse", family: "Amaryllidaceae" },
  { sci: "Hyacinthus orientalis", common: "Jacinthe", family: "Asparagaceae" },
  { sci: "Crocus vernus", common: "Crocus", family: "Iridaceae" },
  { sci: "Lilium candidum", common: "Lis", family: "Liliaceae" },
  { sci: "Gladiolus", common: "Glaieul", family: "Iridaceae" },
  { sci: "Dahlia", common: "Dahlia (tubercule)", family: "Asteraceae" },
  { sci: "Muscari armeniacum", common: "Muscari", family: "Asparagaceae" },
  { sci: "Allium giganteum", common: "Ail d'ornement", family: "Amaryllidaceae" },
  { sci: "Galanthus nivalis", common: "Perce-neige", family: "Amaryllidaceae" },
  { sci: "Hippeastrum", common: "Amaryllis", family: "Amaryllidaceae" },
  { sci: "Begonia tuberhybrida", common: "Begonia tubereux", family: "Begoniaceae" },
  { sci: "Canna indica", common: "Canna", family: "Cannaceae" },

  // ---- Rosiers ----
  { sci: "Rosa", common: "Rosier", family: "Rosaceae" },
  { sci: "Rosa rugosa", common: "Rosier rugueux", family: "Rosaceae" },

  // ---- Arbustes ornementaux ----
  { sci: "Buxus sempervirens", common: "Buis", family: "Buxaceae" },
  { sci: "Rhododendron", common: "Rhododendron", family: "Ericaceae" },
  { sci: "Azalea japonica", common: "Azalee", family: "Ericaceae" },
  { sci: "Camellia japonica", common: "Camelia", family: "Theaceae" },
  { sci: "Hibiscus rosa-sinensis", common: "Hibiscus", family: "Malvaceae" },
  { sci: "Hibiscus syriacus", common: "Althea", family: "Malvaceae" },
  { sci: "Viburnum tinus", common: "Laurier-tin", family: "Adoxaceae" },
  { sci: "Viburnum opulus", common: "Viorne obier", family: "Adoxaceae" },
  { sci: "Forsythia intermedia", common: "Forsythia", family: "Oleaceae" },
  { sci: "Syringa vulgaris", common: "Lilas", family: "Oleaceae" },
  { sci: "Weigela florida", common: "Weigelia", family: "Caprifoliaceae" },
  { sci: "Deutzia gracilis", common: "Deutzia", family: "Hydrangeaceae" },
  { sci: "Philadelphus coronarius", common: "Seringat", family: "Hydrangeaceae" },
  { sci: "Spiraea japonica", common: "Spiree", family: "Rosaceae" },
  { sci: "Cornus alba", common: "Cornouiller blanc", family: "Cornaceae" },
  { sci: "Hydrangea paniculata", common: "Hortensia panicule", family: "Hydrangeaceae" },
  { sci: "Berberis thunbergii", common: "Epine-vinette", family: "Berberidaceae" },
  { sci: "Cotoneaster horizontalis", common: "Cotoneaster", family: "Rosaceae" },
  { sci: "Pyracantha coccinea", common: "Buisson ardent", family: "Rosaceae" },
  { sci: "Euonymus fortunei", common: "Fusain persistant", family: "Celastraceae" },
  { sci: "Mahonia aquifolium", common: "Mahonia", family: "Berberidaceae" },
  { sci: "Skimmia japonica", common: "Skimmia", family: "Rutaceae" },
  { sci: "Nandina domestica", common: "Bambou sacre", family: "Berberidaceae" },
  { sci: "Hamamelis mollis", common: "Hamamelis", family: "Hamamelidaceae" },
  { sci: "Ceanothus thyrsiflorus", common: "Ceanothe, lilas de Californie", family: "Rhamnaceae" },
  { sci: "Callicarpa bodinieri", common: "Arbuste aux bonbons", family: "Lamiaceae" },
  { sci: "Photinia x fraseri", common: "Photinia", family: "Rosaceae" },
  { sci: "Prunus laurocerasus", common: "Laurier-cerise", family: "Rosaceae" },
  { sci: "Aucuba japonica", common: "Aucuba", family: "Garryaceae" },
  { sci: "Choisya ternata", common: "Oranger du Mexique", family: "Rutaceae" },
  { sci: "Pieris japonica", common: "Pieris", family: "Ericaceae" },
  { sci: "Hypericum calycinum", common: "Millepertuis", family: "Hypericaceae" },
  { sci: "Potentilla fruticosa", common: "Potentille arbustive", family: "Rosaceae" },
  { sci: "Caryopteris clandonensis", common: "Barbe-bleue", family: "Lamiaceae" },
  { sci: "Perovskia atriplicifolia", common: "Sauge de Russie", family: "Lamiaceae" },
  { sci: "Ilex aquifolium", common: "Houx", family: "Aquifoliaceae" },
  { sci: "Sambucus nigra", common: "Sureau noir", family: "Adoxaceae" },
  { sci: "Buddleja davidii", common: "Arbre aux papillons", family: "Scrophulariaceae" },

  // ---- Grimpantes ----
  { sci: "Clematis", common: "Clematite", family: "Ranunculaceae" },
  { sci: "Wisteria sinensis", common: "Glycine", family: "Fabaceae" },
  { sci: "Lonicera japonica", common: "Chevrefeuille", family: "Caprifoliaceae" },
  { sci: "Jasminum officinale", common: "Jasmin", family: "Oleaceae" },
  { sci: "Trachelospermum jasminoides", common: "Jasmin etoile", family: "Apocynaceae" },
  { sci: "Parthenocissus tricuspidata", common: "Vigne vierge", family: "Vitaceae" },
  { sci: "Hedera helix", common: "Lierre commun", family: "Araliaceae" },
  { sci: "Passiflora caerulea", common: "Passiflore", family: "Passifloraceae" },
  { sci: "Campsis radicans", common: "Bignone", family: "Bignoniaceae" },
  { sci: "Vitis vinifera", common: "Vigne", family: "Vitaceae" },
  { sci: "Humulus lupulus", common: "Houblon", family: "Cannabaceae" },

  // ---- Haies / coniferes ----
  { sci: "Thuja occidentalis", common: "Thuya", family: "Cupressaceae" },
  { sci: "Cupressocyparis leylandii", common: "Cypres de Leyland", family: "Cupressaceae" },
  { sci: "Taxus baccata", common: "If", family: "Taxaceae" },
  { sci: "Picea abies", common: "Epicea", family: "Pinaceae" },
  { sci: "Picea glauca conica", common: "Sapin nain conique", family: "Pinaceae" },
  { sci: "Pinus mugo", common: "Pin de montagne", family: "Pinaceae" },
  { sci: "Juniperus communis", common: "Genevrier", family: "Cupressaceae" },
  { sci: "Chamaecyparis lawsoniana", common: "Cypres de Lawson", family: "Cupressaceae" },
  { sci: "Carpinus betulus", common: "Charme", family: "Betulaceae" },
  { sci: "Fagus sylvatica", common: "Hetre", family: "Fagaceae" },
  { sci: "Ligustrum ovalifolium", common: "Troene", family: "Oleaceae" },

  // ---- Arbres ornementaux & fruitiers ----
  { sci: "Acer palmatum", common: "Erable du Japon", family: "Sapindaceae" },
  { sci: "Betula pendula", common: "Bouleau", family: "Betulaceae" },
  { sci: "Prunus serrulata", common: "Cerisier du Japon", family: "Rosaceae" },
  { sci: "Malus domestica", common: "Pommier", family: "Rosaceae" },
  { sci: "Pyrus communis", common: "Poirier", family: "Rosaceae" },
  { sci: "Prunus avium", common: "Cerisier", family: "Rosaceae" },
  { sci: "Prunus domestica", common: "Prunier", family: "Rosaceae" },
  { sci: "Olea europaea", common: "Olivier", family: "Oleaceae" },
  { sci: "Citrus limon", common: "Citronnier", family: "Rutaceae" },
  { sci: "Citrus reticulata", common: "Mandarinier", family: "Rutaceae" },
  { sci: "Magnolia soulangeana", common: "Magnolia", family: "Magnoliaceae" },
  { sci: "Cercis siliquastrum", common: "Arbre de Judee", family: "Fabaceae" },
  { sci: "Ginkgo biloba", common: "Ginkgo", family: "Ginkgoaceae" },
  { sci: "Salix caprea", common: "Saule marsault", family: "Salicaceae" },
  { sci: "Cornus florida", common: "Cornouiller a fleurs", family: "Cornaceae" },
  { sci: "Laburnum anagyroides", common: "Cytise", family: "Fabaceae" },

  // ---- Mediterraneennes / terrasse ----
  { sci: "Nerium oleander", common: "Laurier-rose", family: "Apocynaceae" },
  { sci: "Citrus aurantium", common: "Oranger", family: "Rutaceae" },
  { sci: "Bougainvillea glabra", common: "Bougainvillier", family: "Nyctaginaceae" },
  { sci: "Agapanthus africanus", common: "Agapanthe", family: "Amaryllidaceae" },
  { sci: "Lantana camara", common: "Lantana", family: "Verbenaceae" },
  { sci: "Dipladenia", common: "Dipladenia", family: "Apocynaceae" },
  { sci: "Solanum jasminoides", common: "Faux jasmin", family: "Solanaceae" },
  { sci: "Cistus purpureus", common: "Ciste", family: "Cistaceae" },
  { sci: "Phormium tenax", common: "Lin de Nouvelle-Zelande", family: "Asphodelaceae" },
  { sci: "Cordyline australis", common: "Cordyline exterieure", family: "Asparagaceae" },
  { sci: "Trachycarpus fortunei", common: "Palmier de Chine", family: "Arecaceae" },
  { sci: "Chamaerops humilis", common: "Palmier nain", family: "Arecaceae" },

  // ---- Graminees & bambous ----
  { sci: "Miscanthus sinensis", common: "Roseau de Chine", family: "Poaceae" },
  { sci: "Pennisetum alopecuroides", common: "Herbe aux ecouvillons", family: "Poaceae" },
  { sci: "Festuca glauca", common: "Fetuque bleue", family: "Poaceae" },
  { sci: "Stipa tenuissima", common: "Cheveux d'ange", family: "Poaceae" },
  { sci: "Carex morrowii", common: "Laiche", family: "Cyperaceae" },
  { sci: "Cortaderia selloana", common: "Herbe de la pampa", family: "Poaceae" },
  { sci: "Phyllostachys aurea", common: "Bambou dore", family: "Poaceae" },
  { sci: "Fargesia murielae", common: "Bambou non tracant", family: "Poaceae" },

  // ---- Couvre-sol & rocaille ----
  { sci: "Vinca minor", common: "Petite pervenche", family: "Apocynaceae" },
  { sci: "Pachysandra terminalis", common: "Pachysandra", family: "Buxaceae" },
  { sci: "Ajuga reptans", common: "Bugle rampante", family: "Lamiaceae" },
  { sci: "Aubrieta deltoidea", common: "Aubriete", family: "Brassicaceae" },
  { sci: "Iberis sempervirens", common: "Corbeille d'argent", family: "Brassicaceae" },
  { sci: "Armeria maritima", common: "Gazon d'Espagne", family: "Plumbaginaceae" },
  { sci: "Thymus serpyllum", common: "Thym serpolet", family: "Lamiaceae" },
  { sci: "Cerastium tomentosum", common: "Corbeille d'argent duveteuse", family: "Caryophyllaceae" },
  { sci: "Saxifraga arendsii", common: "Saxifrage", family: "Saxifragaceae" },
  { sci: "Dianthus deltoides", common: "Oeillet a delta", family: "Caryophyllaceae" },

  // ---- Aquatiques / berges / carnivores ----
  { sci: "Nymphaea", common: "Nenuphar", family: "Nymphaeaceae" },
  { sci: "Iris pseudacorus", common: "Iris des marais", family: "Iridaceae" },
  { sci: "Typha latifolia", common: "Massette", family: "Typhaceae" },
  { sci: "Dionaea muscipula", common: "Dionee attrape-mouche", family: "Droseraceae" },
  { sci: "Sarracenia purpurea", common: "Sarracenie", family: "Sarraceniaceae" },
  { sci: "Drosera capensis", common: "Rossolis", family: "Droseraceae" }
];
